version: 2

sources:
  - name: jobsd
    schema: RAW 
    tables: 
      - name: BENEFITS
        identifier: RAW_BENEFITS
      - name: COMPANIES
        identifier: RAW_COMPANIES
      - name: COMPANY_INDUSTRIES
        identifier: RAW_COMPANY_INDUSTRIES
      - name: EMPLOYEE_COUNTS
        identifier: RAW_EMPLOYEE_COUNTS
      - name: INDUSTRIES
        identifier: RAW_INDUSTRIES
      - name: JOB_INDUSTRIES
        identifier: RAW_JOB_INDUSTRIES
      - name: JOB_SKILLS
        identifier: RAW_JOB_SKILLS
      - name: POSTINGS
        identifier: RAW_POSTINGS
      - name: SALARIES
        identifier: RAW_SALARIES
      - name: SKILLS
        identifier: RAW_SKILLS